# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RengNews' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'GoogleSignIn'

  # Pods for RengNews

  target 'RengNewsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'RengNews-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RengNews-tvOS

  target 'RengNews-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
